proper condition

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,10 +17,12 @@ jobs:
       run: |
         echo '${{ github.event.issue.body }}' > issue_body
         sed -n '/```test_start/,/```/p' issue_body | sed '/^```/ d' > src/reproduce_issue.rs
-        if [ cargo check --tests ]; then
-          cargo test --release reproduce_issue
+        if cargo check --tests; then
+      	  cargo test --release
         else
-          echo "There are compilation errors in the code block"
+          echo 'There are compilation errors'
+          exit 1
         fi
+
     - name: Print payload
       run: echo "${{ toJson(github) }}"
